apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-manager-deployment
  labels:
    app.kubernetes.io/name: pod-manager-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pod-manager-deployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pod-manager-deployment
    spec:
      containers:
        - name: pod-manager
          image: pod-manager:1.0.0
          imagePullPolicy: IfNotPresent
          command:
          - bash
          - -c
          - |
            while true; do
              echo -n "." 
              sleep 10
            done
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi